[SDKS-9120] Impression per toggle implementation
splitio/go-client pull request #225
Opened 2024-12-11 20:06 UTC by sanzmauro

# GO SDK

## What did you accomplish?

## How do we test the changes introduced in this PR?

## Extra Notes

2025-01-03 17:45 UTC, mmelograno requested changes

2025-01-03 17:45 UTC, mmelograno commented on splitio/client/client.go
> +	impressionManager   *provisional.ImpressionManagerImpl
why not interface?

2025-01-03 17:45 UTC, mmelograno commented on splitio/client/client.go
> +				Impression: c.createImpression(feature, bucketingKey, evaluation.Label, matchingKey, evaluation.Treatment, evaluation.SplitChangeNumber),
createImpressionDecorated for both?

2025-01-03 18:25 UTC, sanzmauro commented on splitio/client/client.go
> +	impressionManager   *provisional.ImpressionManagerImpl
it is to avoid making a  breaking change in commons

2025-01-08 17:57 UTC, sanzmauro commented on splitio/client/client.go
> +				Impression: c.createImpression(feature, bucketingKey, evaluation.Label, matchingKey, evaluation.Treatment, evaluation.SplitChangeNumber),
done

2025-01-17 14:44 UTC, mredolatti approved these changes

2025-01-17 19:17 UTC, nmayorsplit approved these changes

2025-01-17 19:36 UTC, merged